### ISSUE TITLE
misleading error message if log directory is not accessible

### ISSUE THREAD

**Issue by lesinigo** [nginxinc/nginx-ldap-auth#36] opened 2017-12-20 14:30 UTC
Setting the `$LOG` variable to a file in a non-existent directory will result in a message telling me that the non-existent log file does not exist:
```
# rm -rf /var/log/nginx-ldap-auth
# LOG=/var/log/nginx-ldap-auth/daemon.log /usr/bin/nginx-ldap-auth-daemon
/usr/bin/nginx-ldap-auth-daemon: line 2: /var/log/nginx-ldap-auth/daemon.log: No such file or directory
```

The shell code should possibly try to create the directory and/or emit a more explicit message that warns the user that the log directory cannot be accessed.

(IMHO: better yet to get rid of the `/bin/sh` stuff and directly use `#!/usr/bin/env python2` as per [PEP-0394](https://www.python.org/dev/peps/pep-0394/))

**Comment by vl-homutov** [comment] 2017-12-25 10:12
The error message is very clear, and complains exactly about the root cause: missing file or directory.
Various packaging scripts will be fixed to deal correctly with directories they use (i.e. create when needed or have it in dependencies or whatever fix is appropriate).

**Closed by vl-homutov** 2017-12-25 10:13 UTC
